before_script:
  - echo "Building for $MODULECODE"
  - apt-get update -qy
  - apt-get install -y python python-pip python-dev build-essential libfontconfig git openssh-client pandoc
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

build:
  script:
    - pip install --upgrade pip
    - pip install --upgrade virtualenv
    - pip install --no-index -f http://effbot.org/downloads/ -U PIL --trusted-host effbot.org
    - git clone git@mas-gitlab.ncl.ac.uk:makecourse-tools/makecourse.git
    - pip install -r makecourse/requirements.txt
    - pip install git+ssh://git@mas-gitlab.ncl.ac.uk/makecourse-tools/makecourse.git
    - git clone --recursive git@mas-gitlab.ncl.ac.uk:makecourse-tools/MAS2403.git 
    - makecourse -v MAS2403
    - scp -P2210 -r MAS2403/build/* webedit@makara.ncl.ac.uk:/var/www/html/module/MAS2403/