title: "Basic document course"
build_pdf: false
author: "U. Nittest"
institution: "Testing University"
year: 3435
code: "UT0001"
license:
  name: CC-BY 4.0
  url: https://creativecommons.org/licenses/by/4.0/deed.en
  year: 3434
  by: People
structure:
  - type: chapter
    title: "Basic LaTeX document"
    source: test.tex
  - type: chapter
    title: "Basic markdown document"
    source: test.md
