title: "Course structure tests"
build_pdf: false
structure:
  - type: chapter
    title: Duplicated
    source: basic.tex
  - type: chapter
    title: Duplicated
    source: basic2.tex
  - type: chapter
    title: Duplicated
    source: basic2.tex

  - type: chapter
    title: A very long title which would cause problems if not truncated
    source: basic.tex

  - type: chapter
    title: A very long title which looks similar to another when truncated
    source: basic.tex

  - type: part
    title: "A part"
    content:
      - type: chapter
        source: basic.tex
        title: "A chapter"

  - type: part
    title: "A second part"
    content:
      - type: chapter
        source: basic.tex
        title: "A second chapter"

  - type: chapter
    title: Hidden chapter
    source: basic.tex
    is_hidden: true

  - type: part
    title: Hidden part
    is_hidden: true
    content:
      - type: chapter
        title: Not explicitly hidden chapter
        source: basic.tex

  - type: document
    title: Hidden document
    is_hidden: true
    source: document.tex
    splitlevel: 1

  - type: chapter
    title: "a/𝑎𝐚𝒜"
    source: basic.tex
