name: Run the unit tests

# Controls when the workflow will run
on:
  push:
    branches: [ unittests ]
  pull_request:
    branches: [ unittests ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PYTHON_COMMAND: python3

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: .
    
    steps:
      - uses: actions/checkout@v3
      
      - run: pip install -e .
      
      - run: make test
